Feature/add new marker
SenteraLLC/py-radiometric-corrections pull request #33
Opened 2022-12-01 18:57 UTC by dzermas

# Aruco marker support
## What?
Ability to add new aruco marker support when a new reflectance panel needs to be supported.
## Why?
We will be using different kinds/types of reflectance calibration panels. Each panel will have its own aruco marker id.
## PR Checklist
- [x] Merged latest master
- [ ] Updated version number
- [ ] Version numbers match between package ``__version__`` and *pyproject.toml*
- [ ] All private git packages are at their newest version in both *pyproject.toml* and *environment.yml*
- [ ] All git package version numbers match between *pyproject.toml* and *environment.yml*
- [ ] dist/ImageryCorrector.exe has been rebuilt
## Breaking Changes

2022-12-01 18:59 UTC, dzermas commented
Things to do:
* The 12.41 exiftool version download link is broken. Do we update to 12.50?
* Test has not happened yet.
* I do not know how to build an `exe`, @SamCWill will probably have to assist.

2022-12-06 21:58 UTC, zthorson requested changes

2022-12-06 21:58 UTC, zthorson commented on imgcorrect/zenith_co.py
> +sg3144_1_coefficients.extend(
I wonder if we should use the part numbers (either from the manufacturer, or from our system), so it's easier to correlate which coefficients are for which part.

2022-12-07 20:34 UTC, dzermas commented on imgcorrect/zenith_co.py
> +sg3144_1_coefficients.extend(
@zthorson do you have a preference here? I can change the names to whatever.

2022-12-07 22:44 UTC, zthorson commented on imgcorrect/zenith_co.py
> +sg3144_1_coefficients.extend(
I'm talking to Ryan to get a part number for it.  It sounds like the manufacturer part number is the same, but we are going to rev an internal part number.  So once I hear back from Ryan I'll let you know.

2022-12-07 22:45 UTC, zthorson commented on imgcorrect/corrections.py
> +            coeffs = zenith_co.sg3144_2_coefficients
Mostly display it to the log message to help if we have to support someone remotely that needs to run the script.

2022-12-08 16:56 UTC, zthorson commented on imgcorrect/zenith_co.py
> +sg3144_1_coefficients.extend(
Ok, it sounds like we are just tracking this as batches internally in inventory.  So we'd refer to them as `sg3144_batch1` and `sg3144_batch2` which should match production.

2022-12-20 20:58 UTC, dzermas commented on imgcorrect/zenith_co.py
> +sg3144_1_coefficients.extend(
No worries, it is straight forward to add as many as we need. It should be ready for delivery now. Need the executable. Documentation is finalized by @SamCWill.

2022-12-21 21:33 UTC, zthorson approved these changes
exe's are build and verified and should be ready for merging.

2022-12-21 21:59 UTC, merged